package crunch

var TMPL_PIG = `
--
-- This script was auto generated by Crunch.
--
SET parquet.page.size 1048576 -- default. this is your min read/write unit.
SET parquet.block.size 134217728 -- default. your memory budget for buffering data
SET parquet.compression snappy -- or you can use none, gzip, snappy
SET parquet.enable.dictionary true

SET mapreduce.map.memory.mb 2048
SET job.name 'crunch-$inurl'

DEFINE PROCESSOR ` + "`%%process%%`" + ` SHIP('%%process%%');


coll =  STREAM     ( LOAD '$inurl' AS (line:CHARARRAY) )
        THROUGH PROCESSOR
AS (
%%schema%%
);

store coll into '$outurl' USING parquet.pig.ParquetStorer;
`

var TMPL_HIVE = `
--
-- This script was auto generated by Crunch.
--
create external table data(
%%schema%%
)
PARTITIONED BY(dt string)
STORED AS PARQUET
LOCATION '/data';
`
